### PR TITLE
Disable main view

### PR DESCRIPTION
**Pull request by michalpelka**
New gem that simply disable main window rendering.

### CODE REVIEW

**Comment by michalpelka** [comment]
I've tested this contribution with ROS 2 Camera. 
I've asked ROS 2 Camera to produce image with 1000 fps - this will produce the message with maximum frequency of the FPS of GameLauncher:
image

Next, I've run the game launcher with  `--cl_disableMainView=true`, the main window is black, but we have 2x fps.

image

**Comment by michalpelka** [comment]
Sadly, I cannot have RenderDoc to capture of-screen rendered frame :(

**Comment by pijaro** [comment]
Nice results!

**Comment by michalpelka** [comment]
I've changed the disable mechanism, and the camera FOV is moved away from the scene (pointing negative Z).

**Review by pijaro — APPROVED** [review]

**Pull request merged**
